# Generated by Django 5.1.4 on 2024-12-18 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Your first name', max_length=100)),
                ('second_name', models.CharField(help_text='Your second name', max_length=100)),
                ('nickname', models.CharField(help_text='*Nicknames can contain only letters and digits.', max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
