# Generated by Django 5.1.4 on 2024-12-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_alter_account_first_name_alter_account_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='*Email address must be unique.', max_length=100, unique=True),
        ),
    ]
