# Generated by Django 5.1.4 on 2024-12-21 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_parkingavailability_parkingspace_alter_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$randomSalt$hashedPasswordHere', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='second_name',
            field=models.CharField(max_length=30),
        ),
    ]
